#version 450 core
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(r32f, binding = 0) uniform readonly image3D u_pressure;
layout(r32f, binding = 1) uniform readonly image3D u_rhs;
layout(r8ui, binding = 2) uniform readonly uimage3D u_obstacle;
layout(r32f, binding = 3) uniform writeonly image3D u_pressure_out;

layout(push_constant) uniform Params {
    float u_omega;
} params;

void main() {
    ivec3 texel = ivec3(gl_GlobalInvocationID);
    ivec3 size = imageSize(u_pressure);
    if (any(greaterThanEqual(texel, size))) return;
    ivec3 max3 = size - ivec3(1);

    if (texel.x <= 0 || texel.x >= max3.x ||
        texel.y <= 0 || texel.y >= max3.y ||
        texel.z <= 0 || texel.z >= max3.z) {
        imageStore(u_pressure_out, texel, vec4(0.0));
        return;
    }

    uint obs = imageLoad(u_obstacle, texel).r;
    if (obs > 0u) {
        imageStore(u_pressure_out, texel, vec4(0.0));
        return;
    }

    float pc = imageLoad(u_pressure, texel).r;
    float pL = imageLoad(u_pressure, texel - ivec3(1, 0, 0)).r;
    float pR = imageLoad(u_pressure, texel + ivec3(1, 0, 0)).r;
    float pD = imageLoad(u_pressure, texel - ivec3(0, 1, 0)).r;
    float pU = imageLoad(u_pressure, texel + ivec3(0, 1, 0)).r;
    float pB = imageLoad(u_pressure, texel - ivec3(0, 0, 1)).r;
    float pF = imageLoad(u_pressure, texel + ivec3(0, 0, 1)).r;

    float rhs = imageLoad(u_rhs, texel).r;
    float p_new = (pL + pR + pU + pD + pF + pB - rhs) / 6.0;
    p_new = pc * (1.0 - params.u_omega) + p_new * params.u_omega;

    imageStore(u_pressure_out, texel, vec4(p_new));
}
