#version 450 core
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(rgba16f, binding = 0) uniform readonly image3D u_velocity;
layout(rgba16f, binding = 1) uniform writeonly image3D u_velocity_out;

void main() {
    ivec3 texel = ivec3(gl_GlobalInvocationID);
    ivec3 size = imageSize(u_velocity);
    // Write image size and texel.z for diagnostic
    // x-vel = float(size.x), y-vel = float(size.y), z-vel = float(size.z), w-vel = float(texel.z)
    imageStore(u_velocity_out, texel, vec4(float(size.x), float(size.y), float(size.z), float(texel.z)));
}
