#version 450 core
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(rgba16f, binding = 0) uniform readonly image3D u_velocity;
layout(rgba16f, binding = 1) uniform writeonly image3D u_velocity_out;
layout(r8ui,    binding = 2) uniform readonly uimage3D u_obstacle;
layout(r16f,    binding = 3) uniform readonly image3D u_sdf;

layout(push_constant) uniform Params {
    float u_dt;
    float u_unused1;
    float u_unused2;
    float u_unused3;
    vec3 u_inflow_vel;
} params;

void main() {
    ivec3 texel = ivec3(gl_GlobalInvocationID);
    ivec3 size = imageSize(u_velocity);
    if (any(greaterThanEqual(texel, size))) return;

    if (texel.x == 0) {
        imageStore(u_velocity_out, texel, vec4(params.u_inflow_vel, 1.0));
        return;
    }

    // Just copy input for non-x0 cells
    imageStore(u_velocity_out, texel, imageLoad(u_velocity, texel));
}
