#version 450 core
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(r32f, binding = 0) uniform readonly image3D u_tex;
layout(r8ui, binding = 1) uniform readonly uimage3D u_obstacle;
layout(r32f, binding = 2) uniform writeonly image3D u_out;

void main() {
    ivec3 texel = ivec3(gl_GlobalInvocationID);
    ivec3 size = imageSize(u_tex);
    if (any(greaterThanEqual(texel, size))) return;
    uint obs = imageLoad(u_obstacle, texel).r;
    float val = imageLoad(u_tex, texel).r;
    imageStore(u_out, texel, vec4(obs > 0u ? 0.0 : val));
}
