#version 450 core
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(rgba16f, binding = 0) uniform readonly image3D u_result;
layout(rgba16f, binding = 1) uniform readonly image3D u_stage;
layout(rgba16f, binding = 2) uniform writeonly image3D u_k;

void main() {
    ivec3 texel = ivec3(gl_GlobalInvocationID);
    ivec3 size = imageSize(u_result);
    if (any(greaterThanEqual(texel, size))) return;

    vec4 result = imageLoad(u_result, texel);
    vec4 stage = imageLoad(u_stage, texel);
    imageStore(u_k, texel, result - stage);
}
