#version 450 core
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(rgba16f, binding = 0) uniform readonly image3D u_init;
layout(rgba16f, binding = 1) uniform readonly image3D u_k;
layout(rgba16f, binding = 2) uniform writeonly image3D u_out;

layout(push_constant) uniform Params {
    float coeff;
} params;

void main() {
    ivec3 texel = ivec3(gl_GlobalInvocationID);
    ivec3 size = imageSize(u_init);
    if (any(greaterThanEqual(texel, size))) return;

    vec4 init = imageLoad(u_init, texel);
    vec4 k = imageLoad(u_k, texel);
    imageStore(u_out, texel, init + params.coeff * k);
}
